/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 scene.gltf --transform 
Files: scene.gltf [48.62KB] > scene-transformed.glb [164.79KB] (-239%)
Author: Kyyy_24 (https://sketchfab.com/luckyardrianto27)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/baby-cute-alien-1f7cbacd72334158bebba227396442d6
Title: Baby cute alien
*/

import { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Alien(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/alien/scene-transformed.glb')
  const { actions, names } = useAnimations(animations, group)

  useEffect(()=>{
    actions[names[0]].play()
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.material} skeleton={nodes.Object_9.skeleton} position={[0.218, 0.978, 0]} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Outline} skeleton={nodes.Object_10.skeleton} position={[0.218, 0.978, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/alien/scene-transformed.glb')